
insert into Users (username, email, password, birth, user_description, role) values ('kcrowch0', 'kcrowch0@gmail.com', 'fhxz3e9hc4406', '2022-09-14', 'Donec ut mauris eget massa tempor convallis.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('rkezourec1', 'rkezourec1@gmail.com', 'rvgm66s93', '2023-07-17', 'Morbi quis tortor id nulla ultrices aliquet.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('etittershill2', 'etittershill2@gmail.com', 'loy0g89e', '2023-03-18', 'Phasellus in felis.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('bcharter3', 'bcharter3@gmail.com', '29e27n', '2023-01-26', 'Aenean lectus.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('chuortic4', 'chuortic4@gmail.com', 'gsvoq', '2023-08-01', 'Etiam vel augue.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('abrodnecke5', 'abrodnecke5@gmail.com', '66615w2x8k978', '2023-08-05', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('nmcevilly6', 'nmcevilly6@gmail.com', 'c23847294', '2023-04-20', 'Nulla tellus.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('lrockhill7', 'lrockhill7@gmail.com', '212wn3vsw', '2023-04-12', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('ibayford8', 'ibayford8@gmail.com', 'k89g901703jr', '2023-02-20', 'Vivamus in felis eu sapien cursus vestibulum.', 'USER');
insert into Users (username, email, password, birth, user_description, role) values ('agaratty9', 'agaratty9@gmail.com', 'okif', '2022-10-01', 'Vestibulum sed magna at nunc commodo placerat.', 'USER');

insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('90698 Gulseth Trail', 'Room 539', 2, 1, 2, 2, 'vitae', 'Etiam vel augue.', 863827, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('14160 Bunting Junction', 'PO Box 92362', 2, 1, 1, 2, 'at', 'Etiam faucibus cursus urna.', 627966, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('4317 Blackbird Lane', 'Apt 1174', 2, 1, 3, 2, 'sapien', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 354649, 4);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('48 Lillian Point', 'Room 881', 2, 1, 2, 3, 'suspendisse', 'Suspendisse ornare consequat lectus.', 794621, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('5653 Bowman Junction', 'Room 961', 2, 2, 1, 3, 'duis', 'Maecenas tincidunt lacus at velit.', 496356, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('3 Mcguire Junction', 'Apt 1409', 4, 2, 3, 1, 'proin', 'Aliquam quis turpis eget elit sodales scelerisque.', 390762, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('69 Graceland Point', 'Suite 83', 4, 1, 3, 1, 'mi', 'Donec dapibus.', 237301, 8);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('23 Hayes Road', 'PO Box 77406', 3, 2, 1, 3, 'odio', 'Maecenas pulvinar lobortis est.', 900110, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('89339 Maywood Junction', 'PO Box 84793', 4, 2, 4, 3, 'varius', 'Donec dapibus.', 741206, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('489 Goodland Parkway', '14th Floor', 3, 2, 1, 3, 'sed', 'Proin risus.', 752753, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('29269 Di Loreto Pass', '2nd Floor', 3, 2, 3, 2, 'hac', 'Duis mattis egestas metus.', 230813, 4);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('790 Carioca Hill', 'PO Box 40895', 3, 2, 2, 1, 'quisque', 'In blandit ultrices enim.', 896711, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('854 Graceland Place', 'Room 1390', 4, 1, 3, 2, 'tincidunt', 'Nunc rhoncus dui vel sem.', 951283, 4);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('32 Stone Corner Avenue', 'Room 1100', 2, 2, 1, 1, 'sapien', 'Aliquam erat volutpat.', 886407, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('8505 Green Lane', '2nd Floor', 3, 1, 1, 2, 'nonummy', 'Nulla suscipit ligula in lacus.', 414335, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('2228 Gina Terrace', 'Room 84', 2, 2, 4, 1, 'id', 'Aliquam quis turpis eget elit sodales scelerisque.', 233270, 1);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('84 Crest Line Avenue', 'Apt 1584', 3, 1, 3, 1, 'nonummy', 'Cras in purus eu magna vulputate luctus.', 582375, 1);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('36947 Pond Avenue', 'PO Box 49887', 3, 2, 1, 1, 'ante', 'Nulla ut erat id mauris vulputate elementum.', 184528, 8);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('4319 Graedel Place', 'Apt 96', 2, 1, 4, 2, 'aliquam', 'Fusce posuere felis sed lacus.', 798572, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('734 Lakewood Gardens Plaza', 'PO Box 72770', 2, 1, 4, 3, 'dis', 'Cras pellentesque volutpat dui.', 310297, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('7 Jana Point', '17th Floor', 4, 2, 4, 3, 'maecenas', 'Praesent blandit lacinia erat.', 420778, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('39086 Larry Street', 'Apt 391', 2, 1, 4, 2, 'vulputate', 'Integer tincidunt ante vel ipsum.', 524297, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('5487 Dorton Center', 'Apt 1480', 4, 1, 2, 2, 'pulvinar', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 402366, 3);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('56 Kim Parkway', '4th Floor', 4, 1, 2, 3, 'eu', 'Aenean sit amet justo.', 580101, 1);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('6 Walton Terrace', 'Suite 18', 3, 1, 2, 1, 'potenti', 'Morbi non lectus.', 497867, 4);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('7065 Calypso Drive', '2nd Floor', 2, 2, 3, 1, 'pellentesque', 'Duis bibendum.', 497915, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('66 Anzinger Point', '8th Floor', 3, 2, 1, 1, 'consectetuer', 'Pellentesque eget nunc.', 577717, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('5724 Acker Parkway', 'Room 424', 3, 1, 1, 2, 'placerat', 'In sagittis dui vel nisl.', 149716, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('8435 Maryland Park', 'Room 528', 3, 1, 2, 1, 'blandit', 'Praesent blandit.', 697863, 6);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('7511 Sullivan Pass', 'Room 1567', 3, 2, 3, 3, 'quam', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 600367, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('227 Fieldstone Terrace', '20th Floor', 2, 1, 4, 3, 'eget', 'Aliquam non mauris.', 667854, 10);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('7 Blackbird Street', 'PO Box 82101', 2, 1, 4, 1, 'pede', 'Pellentesque at nulla.', 896792, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('0992 Green Ridge Road', 'PO Box 68955', 3, 2, 2, 3, 'consectetuer', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 318045, 3);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('836 Anderson Crossing', '15th Floor', 2, 2, 2, 2, 'ligula', 'Nullam porttitor lacus at turpis.', 666452, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('45909 Jenifer Center', '10th Floor', 2, 2, 3, 2, 'quis', 'Nam dui.', 922217, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('02185 Maple Lane', 'PO Box 24609', 3, 1, 3, 2, 'bibendum', 'Maecenas ut massa quis augue luctus tincidunt.', 464083, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('57 Trailsway Circle', 'Apt 1034', 2, 1, 2, 2, 'donec', 'Mauris sit amet eros.', 299192, 3);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('88 Express Way', 'Suite 79', 3, 2, 1, 1, 'potenti', 'Morbi vel lectus in quam fringilla rhoncus.', 319141, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('18707 Vahlen Plaza', 'Apt 1553', 4, 2, 2, 3, 'sit', 'Donec ut mauris eget massa tempor convallis.', 764144, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('085 Dryden Street', 'Suite 99', 2, 1, 1, 1, 'donec', 'Cras non velit nec nisi vulputate nonummy.', 397558, 3);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('5518 Truax Terrace', 'Room 1204', 4, 2, 3, 2, 'proin', 'Integer ac neque.', 409193, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('40385 8th Crossing', '3rd Floor', 3, 1, 2, 3, 'quam', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 203449, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('17050 American Ash Crossing', '13th Floor', 2, 2, 4, 2, 'turpis', 'Mauris ullamcorper purus sit amet nulla.', 227569, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('8 Westridge Drive', 'PO Box 46555', 4, 1, 4, 3, 'ac', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 419053, 5);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('8 Hazelcrest Road', 'Suite 72', 2, 2, 2, 3, 'nunc', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 229552, 7);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('399 Buhler Crossing', 'Apt 1707', 4, 2, 3, 1, 'quis', 'Vivamus vel nulla eget eros elementum pellentesque.', 829434, 8);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('84 Lakewood Gardens Alley', 'Suite 21', 4, 1, 1, 3, 'ante', 'Ut tellus.', 746699, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('4 Charing Cross Plaza', '17th Floor', 4, 2, 4, 1, 'at', 'Donec ut mauris eget massa tempor convallis.', 503326, 9);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('4 Merry Circle', 'Room 829', 3, 1, 1, 3, 'arcu', 'Aliquam erat volutpat.', 318868, 2);
insert into Accommodation (main_address, detail_address, guest, bedroom, bed, bathroom, acmd_name, acmd_description, price, user_id) values ('6 Dennis Parkway', '9th Floor', 4, 1, 3, 3, 'est', 'Aenean auctor gravida sem.', 897956, 10);

insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/164x100.png/ff4444/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/112x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/190x100.png/dddddd/000000', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/168x100.png/ff4444/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/141x100.png/ff4444/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/108x100.png/ff4444/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/130x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/133x100.png/cc0000/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/187x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/162x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/188x100.png/5fa2dd/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/169x100.png/ff4444/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/116x100.png/ff4444/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/236x100.png/dddddd/000000', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/185x100.png/5fa2dd/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/145x100.png/dddddd/000000', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/202x100.png/5fa2dd/ffffff', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/113x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/158x100.png/dddddd/000000', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/159x100.png/ff4444/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/214x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/134x100.png/ff4444/ffffff', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/244x100.png/ff4444/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/112x100.png/cc0000/ffffff', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/137x100.png/ff4444/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/176x100.png/cc0000/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/217x100.png/dddddd/000000', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/217x100.png/ff4444/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/123x100.png/cc0000/ffffff', 10);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/168x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/225x100.png/5fa2dd/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/148x100.png/ff4444/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/134x100.png/dddddd/000000', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/159x100.png/ff4444/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/176x100.png/ff4444/ffffff', 10);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/200x100.png/ff4444/ffffff', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/131x100.png/cc0000/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/169x100.png/ff4444/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/164x100.png/ff4444/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/132x100.png/cc0000/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/101x100.png/cc0000/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/158x100.png/dddddd/000000', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/241x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/200x100.png/dddddd/000000', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/169x100.png/ff4444/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/215x100.png/5fa2dd/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/207x100.png/5fa2dd/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/143x100.png/dddddd/000000', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/111x100.png/5fa2dd/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/223x100.png/cc0000/ffffff', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/222x100.png/5fa2dd/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/178x100.png/5fa2dd/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/156x100.png/ff4444/ffffff', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/184x100.png/dddddd/000000', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/212x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/229x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/176x100.png/ff4444/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/226x100.png/dddddd/000000', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/198x100.png/cc0000/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/149x100.png/cc0000/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/194x100.png/5fa2dd/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/227x100.png/ff4444/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/120x100.png/5fa2dd/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/241x100.png/dddddd/000000', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/109x100.png/5fa2dd/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/187x100.png/5fa2dd/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/228x100.png/5fa2dd/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/198x100.png/dddddd/000000', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/249x100.png/5fa2dd/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/142x100.png/cc0000/ffffff', 10);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/155x100.png/5fa2dd/ffffff', 10);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/174x100.png/dddddd/000000', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/133x100.png/dddddd/000000', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/237x100.png/5fa2dd/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/198x100.png/cc0000/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/236x100.png/cc0000/ffffff', 10);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/225x100.png/dddddd/000000', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/143x100.png/dddddd/000000', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/127x100.png/ff4444/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/228x100.png/cc0000/ffffff', 8);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/105x100.png/ff4444/ffffff', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/202x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/111x100.png/ff4444/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/195x100.png/ff4444/ffffff', 4);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/167x100.png/cc0000/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/168x100.png/5fa2dd/ffffff', 7);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/125x100.png/dddddd/000000', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/195x100.png/cc0000/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/166x100.png/ff4444/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/104x100.png/ff4444/ffffff', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/246x100.png/cc0000/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/177x100.png/dddddd/000000', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/171x100.png/cc0000/ffffff', 6);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/138x100.png/cc0000/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/159x100.png/cc0000/ffffff', 3);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/185x100.png/dddddd/000000', 9);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/179x100.png/ff4444/ffffff', 2);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/130x100.png/5fa2dd/ffffff', 5);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/120x100.png/ff4444/ffffff', 1);
insert into image (acmd_image_url, accommodation_id) values ('http://dummyimage.com/221x100.png/ff4444/ffffff', 1);

insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-22', '2023-08-07', '960.569', 3, true, 6, 8);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-09', '2023-08-01', '705.754', 2, true, 2, 2);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-25', '2023-08-17', '867.588', 2, true, 10, 8);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-10', '2023-08-06', '107.176', 4, false, 8, 1);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-10', '2023-08-21', '142.845', 2, true, 9, 10);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-08', '2023-08-10', '810.993', 3, false, 8, 7);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-09', '2023-08-30', '941.143', 4, false, 6, 3);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-25', '2023-08-07', '904.027', 2, true, 1, 5);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-05', '2023-08-16', '421.957', 3, false, 8, 2);
insert into reservation (check_in, check_out, total_price, guest, is_deleted, user_id, accommodation_id) values ('2023-07-30', '2023-08-23', '237.850', 2, false, 2, 2);

insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Praesent id massa id nisl venenatis lacinia.', 5, '2023-07-05', 7, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus in felis eu sapien cursus vestibulum.', 2, '2023-04-08', 7, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 5, '2023-07-27', 2, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin eu mi.', 5, '2023-02-25', 2, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi non lectus.', 3, '2022-12-07', 8, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis ac nibh.', 3, '2023-04-10', 3, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris sit amet eros.', 3, '2023-07-30', 3, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla facilisi.', 3, '2023-01-20', 5, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Suspendisse potenti.', 5, '2023-05-16', 8, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus vel nulla eget eros elementum pellentesque.', 1, '2023-05-01', 5, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec posuere metus vitae ipsum.', 5, '2022-09-25', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 4, '2023-03-19', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In blandit ultrices enim.', 2, '2022-11-12', 6, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce consequat.', 1, '2023-06-14', 9, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 5, '2023-07-08', 6, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis aliquam convallis nunc.', 1, '2022-11-22', 2, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis at velit eu est congue elementum.', 3, '2022-10-07', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris ullamcorper purus sit amet nulla.', 3, '2022-09-03', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5, '2023-07-05', 2, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1, '2023-04-23', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam erat volutpat.', 1, '2023-01-16', 9, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer tincidunt ante vel ipsum.', 3, '2023-03-25', 9, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4, '2023-05-13', 4, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, '2023-04-17', 3, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc nisl.', 5, '2022-10-23', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 2, '2023-04-12', 1, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam tristique tortor eu pede.', 4, '2023-06-14', 5, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur gravida nisi at nibh.', 2, '2023-05-15', 1, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla justo.', 3, '2023-05-07', 3, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras in purus eu magna vulputate luctus.', 3, '2023-04-16', 9, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 1, '2023-05-28', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 5, '2023-01-03', 5, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean lectus.', 4, '2022-11-19', 6, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla tellus.', 2, '2023-02-19', 4, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, '2023-04-29', 9, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 3, '2023-05-23', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2, '2022-11-16', 4, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec posuere metus vitae ipsum.', 4, '2023-05-11', 6, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Ut tellus.', 2, '2023-07-02', 9, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed accumsan felis.', 3, '2022-12-26', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur convallis.', 4, '2022-11-02', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas rhoncus aliquam lacus.', 4, '2023-04-05', 4, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus vestibulum sagittis sapien.', 3, '2023-04-17', 8, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', 2, '2023-05-22', 1, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 2, '2023-03-13', 9, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 4, '2022-09-19', 5, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 1, '2023-07-08', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 1, '2023-06-11', 7, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1, '2023-01-31', 6, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam faucibus cursus urna.', 2, '2022-11-09', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean fermentum.', 3, '2022-12-11', 7, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', 4, '2022-08-22', 5, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 4, '2023-05-23', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In hac habitasse platea dictumst.', 5, '2022-09-15', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 2, '2023-04-01', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 3, '2023-01-03', 5, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, '2023-03-13', 9, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi vel lectus in quam fringilla rhoncus.', 1, '2022-10-18', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc purus.', 4, '2022-11-23', 1, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Pellentesque at nulla.', 4, '2022-09-26', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc purus.', 3, '2023-05-31', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer ac neque.', 4, '2023-05-16', 8, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur convallis.', 5, '2023-05-24', 1, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam faucibus cursus urna.', 3, '2023-04-03', 2, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 5, '2023-04-11', 2, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 4, '2022-10-28', 7, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer ac neque.', 2, '2022-12-11', 10, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 4, '2023-03-03', 8, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 5, '2022-11-11', 2, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque ut erat.', 2, '2022-11-16', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Phasellus in felis.', 2, '2023-04-27', 7, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 3, '2023-04-08', 6, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam quis turpis eget elit sodales scelerisque.', 5, '2023-04-27', 10, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2022-11-15', 10, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Suspendisse accumsan tortor quis turpis.', 2, '2023-05-02', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi ut odio.', 2, '2022-09-01', 8, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin eu mi.', 3, '2022-09-10', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2, '2023-04-14', 5, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 1, '2022-10-03', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean lectus.', 2, '2022-12-28', 8, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Praesent blandit.', 3, '2023-03-16', 9, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 3, '2022-12-08', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vestibulum sed magna at nunc commodo placerat.', 5, '2022-10-01', 9, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 4, '2023-08-12', 10, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam justo.', 5, '2022-11-21', 5, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce posuere felis sed lacus.', 3, '2022-12-22', 8, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In quis justo.', 2, '2023-03-05', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In blandit ultrices enim.', 4, '2022-11-06', 6, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5, '2023-02-14', 6, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 2, '2023-01-17', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Pellentesque viverra pede ac diam.', 2, '2022-09-19', 2, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras non velit nec nisi vulputate nonummy.', 1, '2023-04-21', 4, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla facilisi.', 3, '2023-07-18', 10, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 1, '2023-07-07', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, '2022-12-21', 3, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas ut massa quis augue luctus tincidunt.', 5, '2023-01-21', 3, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec semper sapien a libero.', 4, '2023-06-25', 9, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam molestie nibh in lectus.', 2, '2023-07-25', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi non lectus.', 5, '2023-02-12', 8, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2, '2023-05-16', 7, 1);

