insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Praesent id massa id nisl venenatis lacinia.', 5, '2023-07-05', 7, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus in felis eu sapien cursus vestibulum.', 2, '2023-04-08', 7, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 5, '2023-07-27', 2, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin eu mi.', 5, '2023-02-25', 2, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi non lectus.', 3, '2022-12-07', 8, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis ac nibh.', 3, '2023-04-10', 3, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris sit amet eros.', 3, '2023-07-30', 3, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla facilisi.', 3, '2023-01-20', 5, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Suspendisse potenti.', 5, '2023-05-16', 8, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus vel nulla eget eros elementum pellentesque.', 1, '2023-05-01', 5, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec posuere metus vitae ipsum.', 5, '2022-09-25', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 4, '2023-03-19', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In blandit ultrices enim.', 2, '2022-11-12', 6, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce consequat.', 1, '2023-06-14', 9, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 5, '2023-07-08', 6, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis aliquam convallis nunc.', 1, '2022-11-22', 2, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Duis at velit eu est congue elementum.', 3, '2022-10-07', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris ullamcorper purus sit amet nulla.', 3, '2022-09-03', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5, '2023-07-05', 2, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1, '2023-04-23', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam erat volutpat.', 1, '2023-01-16', 9, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer tincidunt ante vel ipsum.', 3, '2023-03-25', 9, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4, '2023-05-13', 4, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, '2023-04-17', 3, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc nisl.', 5, '2022-10-23', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 2, '2023-04-12', 1, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam tristique tortor eu pede.', 4, '2023-06-14', 5, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur gravida nisi at nibh.', 2, '2023-05-15', 1, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla justo.', 3, '2023-05-07', 3, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras in purus eu magna vulputate luctus.', 3, '2023-04-16', 9, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 1, '2023-05-28', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 5, '2023-01-03', 5, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean lectus.', 4, '2022-11-19', 6, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla tellus.', 2, '2023-02-19', 4, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, '2023-04-29', 9, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 3, '2023-05-23', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2, '2022-11-16', 4, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec posuere metus vitae ipsum.', 4, '2023-05-11', 6, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Ut tellus.', 2, '2023-07-02', 9, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed accumsan felis.', 3, '2022-12-26', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur convallis.', 4, '2022-11-02', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas rhoncus aliquam lacus.', 4, '2023-04-05', 4, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vivamus vestibulum sagittis sapien.', 3, '2023-04-17', 8, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', 2, '2023-05-22', 1, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 2, '2023-03-13', 9, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 4, '2022-09-19', 5, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 1, '2023-07-08', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 1, '2023-06-11', 7, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1, '2023-01-31', 6, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam faucibus cursus urna.', 2, '2022-11-09', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean fermentum.', 3, '2022-12-11', 7, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', 4, '2022-08-22', 5, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 4, '2023-05-23', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In hac habitasse platea dictumst.', 5, '2022-09-15', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean sit amet justo.', 2, '2023-04-01', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 3, '2023-01-03', 5, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, '2023-03-13', 9, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi vel lectus in quam fringilla rhoncus.', 1, '2022-10-18', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc purus.', 4, '2022-11-23', 1, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Pellentesque at nulla.', 4, '2022-09-26', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nunc purus.', 3, '2023-05-31', 10, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer ac neque.', 4, '2023-05-16', 8, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Curabitur convallis.', 5, '2023-05-24', 1, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam faucibus cursus urna.', 3, '2023-04-03', 2, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 5, '2023-04-11', 2, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 4, '2022-10-28', 7, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Integer ac neque.', 2, '2022-12-11', 10, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 4, '2023-03-03', 8, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 5, '2022-11-11', 2, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Quisque ut erat.', 2, '2022-11-16', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Phasellus in felis.', 2, '2023-04-27', 7, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 3, '2023-04-08', 6, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam quis turpis eget elit sodales scelerisque.', 5, '2023-04-27', 10, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2022-11-15', 10, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Suspendisse accumsan tortor quis turpis.', 2, '2023-05-02', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi ut odio.', 2, '2022-09-01', 8, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Proin eu mi.', 3, '2022-09-10', 8, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2, '2023-04-14', 5, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 1, '2022-10-03', 9, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aenean lectus.', 2, '2022-12-28', 8, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Praesent blandit.', 3, '2023-03-16', 9, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Sed ante.', 3, '2022-12-08', 2, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Vestibulum sed magna at nunc commodo placerat.', 5, '2022-10-01', 9, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec dapibus.', 4, '2023-08-12', 10, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Etiam justo.', 5, '2022-11-21', 5, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce posuere felis sed lacus.', 3, '2022-12-22', 8, 3);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In quis justo.', 2, '2023-03-05', 8, 5);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('In blandit ultrices enim.', 4, '2022-11-06', 6, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5, '2023-02-14', 6, 2);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 2, '2023-01-17', 5, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Pellentesque viverra pede ac diam.', 2, '2022-09-19', 2, 6);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Cras non velit nec nisi vulputate nonummy.', 1, '2023-04-21', 4, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nulla facilisi.', 3, '2023-07-18', 10, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Aliquam non mauris.', 1, '2023-07-07', 1, 9);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, '2022-12-21', 3, 8);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Maecenas ut massa quis augue luctus tincidunt.', 5, '2023-01-21', 3, 1);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Donec semper sapien a libero.', 4, '2023-06-25', 9, 7);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Nullam molestie nibh in lectus.', 2, '2023-07-25', 10, 4);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Morbi non lectus.', 5, '2023-02-12', 8, 10);
insert into review (comment, rating, created_at, user_id, accommodation_id) values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2, '2023-05-16', 7, 1);
